### PR TITLE
add support for downloading ensime server dependencies and ensime-ser…

### PR DESCRIPTION
**Pull request by gerritjvv**
…ver-jars

### CODE REVIEW

**Comment by gerritjvv** [comment]
related to https://github.com/ensime/ensime.github.io/pull/216

**Comment by fommil** [comment]
cool! Hopefully @coacoas can review. How do you get the scala library/compiler/scalap jars?

**Comment by gerritjvv** [comment]
going to fix the unit test failures, I use the same grails build to download the dependencies. The ensime dep is added to its own configuration (to no interfere with the current project deps) and then grails downloads all its deps and copy them into a separate dir.

https://github.com/ensime/ensime-gradle/pull/64/files#diff-2fd3976071b2f1c6e5b7a5dc6b5cbac2R39

https://github.com/ensime/ensime-gradle/pull/64/files#diff-2fd3976071b2f1c6e5b7a5dc6b5cbac2R57

**Comment by gerritjvv** [comment]
I think the tests fail due to issues not related to this PR. My time is limited with this, and I have limited knowledge of the Ensime codebase itself (tbh just trying to get java working in emacs and I'm new to emacs :) ) but with some help I'll keep on contributing to make this  PR work.

**Comment by fommil** [comment]
I wish I could help but I don't have a clue about gradle. Hopefully some of the existing ensime-gradle authors will chip in

**Comment by coacoas** [comment]
Apologies for not getting to this sooner, @gerritjvv.  Hopefully, I'll have some time to help out with this tonight (US EDT).

**Comment by coacoas** [comment]
@gerritjvv When you see unhelpful error messages like that, it is very useful to run your build with `--info`, which will print out the error messages from the test builds.  In this case, I get: 
```
    11:17:18.399 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
    11:17:18.401 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
    11:17:18.401 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
    11:17:18.401 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
    11:17:18.402 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':ensime'.
    11:17:18.402 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve all dependencies for configuration ':ensime'.
    11:17:18.402 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Cannot resolve external dependency org.ensime:server_2.11:1.0.1 because no repositories are defined.
    11:17:18.402 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]      Required by:
    11:17:18.402 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          project :
```

**Comment by gerritjvv** [comment]
thanks @coacoas I'm rerunning with --info and making some modifications.

**Comment by gerritjvv** [comment]
@coacoas @fommil build seems to work and check passes. travis has failed on jdk1.8 (https://travis-ci.org/ensime/ensime-gradle/jobs/226604060) but works with builds jdk1.7 and openjdk1.7. 

I can't see any error messages that would show why it fails, maybe you can re-trigger the build?

**Comment by fommil** [comment]
that's great! Thank you for picking this up.

**Comment by coacoas** [comment]
@gerritjvv 
Thanks!  One thing - there aren't any tests in this PR.  Could you add some to make sure the correct values are being written out to the `.ensime` file?

**Comment by gerritjvv** [comment]
ok, I'll write a test to check for the server jars.

**Comment by gerritjvv** [comment]
@coacoas plz see the latest commit, I made a test to check that server jars are written and also fixed a cast issue in one of the test cases. I did try to make a more in-depth test but didn't get it to work really and dropped it.

**Comment by coacoas** [comment]
OK, I'll take a look as soon as I can.  The earliest I can look at it would
be in about 10 hours, though.

**Review by coacoas — APPROVED** [review]

**Comment by coacoas** [comment]
@gerritjvv Merged.  I"m sorry this took so long - thanks for taking this up!  I really appreciate it.

**Pull request merged**
