### PR TITLE
Updating the build process

### LINKED ISSUE #30: CI is deploying on all builds
Shouldn't be a big deal, since I have sourceCompatibility and targetCompatibility set, but it's wasteful that I'm deploying four snapshot builds for each deploy.  I should only deploy from the jdk6 build (for android)

### PR DESCRIPTION
**Pull request by coacoas**
Fixes #30

### CODE REVIEW

**Comment by fommil** [comment]
is drone not working for you? The machines are way more powerful than the travis machines.

**Comment by coacoas** [comment]
I looked at it, and there was some reason I preferred travis.  I don't remember off the top of my head what it was, though. Let me investigate and I'll see if I can find it .

**Comment by coacoas** [comment]
I think the main reason I liked it was the build matrix (ability to easily build against multiple JDK versions).  Another thing I really like that I don't see immediately for drone is the ability to cache the dependencies so I don't constantly have to download them.  I saw something in the docs about being able to build against your own docker image, though, but I don't see immediately how to do that.

**Comment by coacoas** [comment]
And, hey, look -- matrix builds http://blog.drone.io/post/drone-0.4-plugins-matrix-compose/

**Comment by coacoas** [comment]
OK. Found the docs on the .drone.yml file and that looks much nicer than just using the dashboard configuration things on their site.  I'll look into this more later today.

**Comment by fommil** [comment]
ensime-docker for our images

**Pull request merged**
